### PR TITLE
Oracle support

### PR DESCRIPTION
**Pull request by humbertodias**
New types: VARCHAR2 and NUMBER

oracle-fix

### CODE REVIEW

**Comment by humbertodias** [comment]
Oracle Tests OK
oracle-ok

Mysql OK
mysql-ok

PostGres
postgres-ok

SQLite
sqlite-ok

Docker script used for create the databases and tests
[docker-dbs.txt](https://github.com/kolchagov/java-crud-api/files/1845465/docker-dbs.txt)

**Comment by kolchagov** [comment]
Thanks for contribution! There are some problems though:
You've changed some test cases (and sqlite dump), which leads to different behaviour...
You are mapping NUMERIC to float/double - unfortunately this isn't correct and can cause precision problems. They are mapped as String for a purpose (client can map them according to its needs to Float/Double/BigDecimal).
It will take some time to merge it - I have to review the changes and maintain compatibility with php-crud-api

**Comment by kolchagov** [comment]
Merged manually, please rebase to master branch.

**Comment by mevdschee** [comment]
Just a small bit of advice: Manual merges hide proper contribution statistics. If you do manually merge (locally), then afterwards automatic merge and overwrite the merged source code with your manual merge (local copy). This way the contributor is shown as properly by github, which is in this case, well deserved. 

Anyway.. congrats on the contribution and the merge!

**Pull request closed without merging**
